export const COUNTRY_PICKER_TOOLBAR_HEIGHT = 50;
export const COUNTRY_PICKER_INPUT_HEIGHT = 275;

export const COUNTRY_PICKER_VIEW_HEIGHT =
  COUNTRY_PICKER_TOOLBAR_HEIGHT + COUNTRY_PICKER_INPUT_HEIGHT;
